# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  coc-diagnostic = nodeEnv.buildNodePackage {
    name = "coc-diagnostic";
    packageName = "coc-diagnostic";
    version = "0.13.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/coc-diagnostic/-/coc-diagnostic-0.13.0.tgz";
      sha512 = "09jUr50HgKBPxlK88p6CrJXGdu5owMT5c951Ajxwp2lhmFlo26NYn5eVo69shEaZvkpFvlskQWn5lqvrDox0Vw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "diagnostic-languageserver extension for coc.nvim";
      homepage = "https://github.com/iamcco/coc-diagnostic#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}