#!/usr/bin/env bash
set -uexo pipefail

BASEURL=https://raw.githubusercontent.com/t184256/nix-configs/staging

[[ -d ~/.ssh ]] || install -m 700 -d ~/.ssh
if [[ ! -e ~/.ssh/authorized_keys ]]; then
  curl $BASEURL/misc/pubkeys/ssh > ~/.ssh/authorized_keys
  chmod 600 ~/.ssh/authorized_keys
fi
