#!/usr/bin/env bash
set -xEeuo pipefail; shopt -s inherit_errexit

# boot into cookie

IP=$1
PORT=${2:-2222}
[[ $IP =~ [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ ]]
: "${REMOTE_USER:=root}"
hostname=plum

if ! command -v dasel >/dev/null; then
  dasel=$(nix build --print-out-paths --no-link 'nixpkgs#dasel') || exit $?
  PATH=$PATH:$dasel/bin
fi

ssh -p "$PORT" "$REMOTE_USER@$IP" "
  set -xEeuo pipefail; shopt -s inherit_errexit
  [[ \"\$(sudo cat /sys/devices/virtual/dmi/id/product_uuid)\" \
    == '7b831688-a568-a517-a43b-345a60bd7e5f' ]]
  [[ -e '/dev/disk/by-id/nvme-Samsung_SSD_990_EVO_Plus_1TB_S7U4NU1YB17701K_1' ]]
  [[ ! -e '/mnt/secrets' ]]
"

# TODO: far future: also reinstall if there's no service data checked out
echo 1>&2 "THIS WILL ERASE ALL DATA ON $1!"

injdir=$(mktemp -d) || exit $?
trap 'sudo rm -rf "$injdir"' EXIT

mkdir -p "$injdir/mnt/secrets"
misc/secrets inject-to-dir "$hostname" "$injdir/mnt/secrets"
[[ -e "$injdir/mnt/secrets/login/monk" ]]
[[ -e "$injdir/mnt/secrets/login/root" ]]
[[ -e "$injdir/mnt/secrets/network-manager" ]]
[[ -e "$injdir/mnt/secrets/sshd/ed25519" ]]
grep -qF 'OPENSSH PRIVATE KEY' "$injdir/mnt/secrets/sshd/ed25519"
find "$injdir/mnt/secrets" -type d -exec chmod 500 {} \;
# will be fixed up to 400 later or on latter secrets injections
# clevis JWE is written to /mnt/secrets/clevis by disko postMountHook

dd if=/dev/urandom bs=64 count=1 status=none \
  > "$injdir/mnt/secrets/root.luks"

mkdir "$injdir/etc"
scp -q -P "$PORT" "$REMOTE_USER@$IP:/etc/machine-id" "$injdir/etc/machine-id"

nix run 'nixpkgs#nixos-anywhere' -- \
  --extra-files "$injdir" \
  --flake ".#$hostname" \
  --kexec /dev/null \
  --disk-encryption-keys "/tmp/root.luks" "$injdir/mnt/secrets/root.luks" \
  --ssh-port "$PORT" \
  "$REMOTE_USER@$IP"

sed -i "/^\[$IP\]:$PORT /d" ~/.ssh/known_hosts
pubkey="$(dasel -f misc/pubkeys/sshd.toml "$hostname" -w -)"
echo "[$IP]:$PORT $pubkey" >> ~/.ssh/known_hosts

# the promised fix-up
for i in {120..1}; do echo 1>&2 -n "$i... "; sleep 1; done
ssh -p "$PORT" "monk@$IP" 'sudo find /mnt/secrets -type d -exec chmod 400 {} \;'
