#!/usr/bin/env bash

set -uexo pipefail

# emmc: /boot, encrypted / (unlocked automatically)
# nvme: encrypted data, encrypted swap (unlocked manually, setup separately)

### Parameters ###

: "${BOOT_SIZE:=768MB}"
: "${HOST:=QUINCE}"
: "${COPY_ETC_NIXOS:=1}"
: "${DISK:=/dev/mmcblk0}"
: "${AUTOPART:=0}"
: "${ENCRYPTION_PASSPHRASE:=}"

### Safeguards ###

[[ "$(sudo cat /sys/devices/virtual/dmi/id/product_uuid)" \
	== '86a6297f-1e97-124f-9435-a77e07c3508d' ]]
[[ -e ${DISK} ]]

### Cleanup ###

cleanup() {
	sudo rm -f /tmp/root.key || true
	sudo umount /mnt/boot 2>/dev/null || true
	sudo cryptsetup close ${HOST} 2>/dev/null || true
	sudo umount /mnt/0 2>/dev/null || true
	sudo umount /mnt/tgt/home 2>/dev/null || true
	sudo umount /mnt/tgt/nix 2>/dev/null || true
	sudo umount /mnt/tgt/persist 2>/dev/null || true
	sudo umount /mnt/persist 2>/dev/null || true
	sudo umount /mnt/tgt/dev/pts 2>/dev/null || true
	sudo umount /mnt/tgt/dev 2>/dev/null || true
	sudo umount /mnt/tgt/proc 2>/dev/null || true
	sudo umount /mnt/tgt/sys/firmware/efi/efivars 2>/dev/null || true
	sudo umount /mnt/tgt/sys 2>/dev/null || true
	sudo umount /mnt/tgt/boot 2>/dev/null || true
	sudo umount -R /mnt/tgt 2>/dev/null || true
}
trap 'set +x; cleanup' EXIT

### Injecting old secrets ###

if [[ ! -e /tmp/old-secrets ]]; then
	if [[ -e "/dev/disk/by-partlabel/${HOST}" ]]; then
		if sudo mount "/dev/disk/by-partlabel/${HOST}" /mnt; then
			if [[ -e /mnt/secrets ]]; then
				cp -rva /mnt/secrets /tmp/old-secrets
			fi
			umount /mnt
		fi
	fi
fi

### Obtaining passphrase ###

if [[ -z "$ENCRYPTION_PASSPHRASE" ]]; then
	read -rsp 'Passphrase: ' ENCRYPTION_PASSPHRASE
fi
[[ -n "$ENCRYPTION_PASSPHRASE" ]]

### Partitioning ###

PARTITIONS=$(sudo fdisk -l "${DISK}")
grep -F '247463936000 bytes, 483328000 sectors' \
	<<<"$PARTITIONS"  # extra safeguard

if grep -F Size <<<"$PARTITIONS"; then
	echo "Existing partition table found on '$DISK'"
	[[ -e "${DISK}p1" ]]
else
	[[ ! -e "${DISK}p1" ]]
	if [[ "$AUTOPART" != 1 ]]; then
		part_prompt='Partition table does not exist,'
		part_prompt+=' auto-partition and lose all data? [y/N] '
		read -rp "$part_prompt" CONFIRMATION
		[[ "$CONFIRMATION" == y ]]; unset CONFIRMATION
	fi
	sudo parted -s ${DISK} -- mklabel gpt
	sudo parted ${DISK} -- mkpart primary fat32 1MB $BOOT_SIZE
	sudo parted ${DISK} -- set 1 esp on
	sudo parted ${DISK} -- name 1 ${HOST}_BOOT
	sudo parted ${DISK} -- mkpart primary xfs $BOOT_SIZE 100%
	sudo parted ${DISK} -- name 2 ${HOST}
	sudo partprobe -s
	[[ -e /dev/disk/by-partlabel/${HOST}_BOOT ]] || sleep 1
	[[ -e /dev/disk/by-partlabel/${HOST} ]] || sleep 1
	[[ -e /dev/disk/by-partlabel/${HOST}_BOOT ]] || sleep 1
	[[ -e /dev/disk/by-partlabel/${HOST} ]] || sleep 1
	sleep 1
	sudo mkfs.fat -F 32 -n ${HOST:0:6}_BOOT \
		/dev/disk/by-partlabel/${HOST}_BOOT
	echo -n "$ENCRYPTION_PASSPHRASE" | \
		sudo cryptsetup -q luksFormat \
			/dev/disk/by-partlabel/${HOST} -d-
	dd if=/dev/random bs=64 count=1 of=/tmp/root.key
	chmod 400 /tmp/root.key
	sudo chown root:root /tmp/root.key
	echo -n "$ENCRYPTION_PASSPHRASE" | \
		sudo cryptsetup -q open \
			/dev/disk/by-partlabel/${HOST} ${HOST} -d-
	echo -n "$ENCRYPTION_PASSPHRASE" | \
		sudo cryptsetup -q luksAddKey \
			/dev/disk/by-partlabel/${HOST} /tmp/root.key
	sudo mkfs.xfs -f -L ${HOST} /dev/mapper/${HOST}
fi

[[ -e /dev/disk/by-partlabel/${HOST}_BOOT ]]
[[ -e /dev/disk/by-partlabel/${HOST} ]]

if [[ ! -e /dev/mapper/${HOST} ]]; then
	echo -n "$ENCRYPTION_PASSPHRASE" | \
		sudo cryptsetup -q open \
			/dev/disk/by-partlabel/${HOST} ${HOST} -d-
fi

# no swap

### Mounting and subvolume creation ###

sudo mkdir -p /mnt/0
sudo mount /dev/mapper/${HOST} /mnt/0

sudo mkdir -p /mnt/0/nix
sudo mkdir -p /mnt/0/home
sudo mkdir -p /mnt/0/secrets

sudo mkdir -p /mnt/tgt
sudo mount -t tmpfs tmpfs /mnt/tgt
sudo mkdir -p /mnt/tgt/{boot,nix,home,mnt/persist}
sudo mkdir -p /mnt/persist  # hack to soothe impermanence
sudo mount --bind /mnt/0/nix /mnt/tgt/nix
sudo mount --bind /mnt/0/home /mnt/tgt/home
sudo mount --bind /mnt/0 /mnt/tgt/mnt/persist
sudo mount --bind /mnt/0 /mnt/persist  # HACK
sudo mount /dev/disk/by-partlabel/${HOST}_BOOT /mnt/tgt/boot
sudo mkdir -p /mnt/tgt/{dev,proc,sys}
sudo mount --bind /dev /mnt/tgt/dev
sudo mount --bind /dev/pts /mnt/tgt/dev/pts
sudo mount --bind /proc /mnt/tgt/proc
sudo mount --bind /sys /mnt/tgt/sys
sudo mount --bind /sys/firmware/efi/efivars \
	/mnt/tgt/sys/firmware/efi/efivars

### Impermanence data injection ###

sudo mkdir -p /mnt/tgt/mnt/persist/etc
# /mnt/persist/secrets/login:
sudo mkdir -p /mnt/tgt/mnt/persist/secrets/login
if [ ! -e /mnt/tgt/mnt/persist/secrets/login/monk ]; then
	echo 'configuring `monk` user'
	mkpasswd -s <<<"$ENCRYPTION_PASSPHRASE" \
		| sudo tee /mnt/tgt/mnt/persist/secrets/login/monk
	sudo chmod 600 /mnt/tgt/mnt/persist/secrets/login/monk
fi
if [ ! -e /mnt/tgt/mnt/persist/secrets/login/root ]; then
	echo 'configuring `root` user'
	mkpasswd -s <<<"$ENCRYPTION_PASSPHRASE" \
		| sudo tee /mnt/tgt/mnt/persist/secrets/login/root
	sudo chmod 600 /mnt/tgt/mnt/persist/secrets/login/root
fi
if [ ! -e /mnt/tgt/mnt/persist/secrets/root.key ]; then
	sudo mv /tmp/root.key /mnt/tgt/mnt/persist/secrets/root.key
fi

# /etc/machine-id:
[[ -e /mnt/tgt/mnt/persist/etc/machine-id ]] || \
	sudo systemd-machine-id-setup --root /mnt/tgt/mnt/persist
# /etc/nixos:
if [[ "$COPY_ETC_NIXOS" == 1 ]]; then
	if git rev-parse --show-toplevel 2>/dev/null; then
		FLAKE=$(git rev-parse --show-toplevel)
		sudo rm -d /mnt/tgt/mnt/persist/etc/nixos 2>/dev/null || true
		[[ -e /mnt/tgt/mnt/persist/etc/nixos ]] || \
			sudo cp -r "$FLAKE" /mnt/tgt/mnt/persist/etc/nixos
	else
		FLAKE='/mnt/tgt/mnt/persist/etc/nixos'
		[[ -e /mnt/tgt/mnt/persist/etc/nixos ]] || \
			sudo git clone https://github.com/t184256/nix-configs \
				-b staging \
				/mnt/tgt/mnt/persist/etc/nixos
	fi
	sudo chown -R 1000:100 /mnt/tgt/mnt/persist/etc/nixos
else
	FLAKE='github:t184256/nix-configs?ref=staging'
fi
# /etc/NetworkManager:
[[ -e /mnt/tgt/mnt/persist/etc/NetworkManager ]] || \
	sudo cp -rv /etc/NetworkManager -t /mnt/tgt/mnt/persist/etc
sudo ls -lt /mnt/tgt/mnt/persist/etc/NetworkManager
# /etc/ssh:
if [[ ! -e /mnt/tgt/mnt/persist/etc/ssh_host_rsa_key ]]; then
	sudo ssh-keygen -t rsa -b 4096 -N '' \
		-f /mnt/tgt/mnt/persist/etc/ssh_host_rsa_key
	sudo chmod 700 /mnt/tgt/mnt/persist/etc/ssh_host_rsa_key
fi
if [[ ! -e /mnt/tgt/mnt/persist/etc/ssh_host_ed25519_key ]]; then
	sudo ssh-keygen -t ed25519 -N '' \
		-f /mnt/tgt/mnt/persist/etc/ssh_host_ed25519_key
	sudo chmod 700 /mnt/tgt/mnt/persist/etc/ssh_host_ed25519_key
fi

### Installation from a flake ###

NIXOS_URL=https://cache.nixos.org?priority=200
HYDRA_URL=https://hydra.unboiled.info
NIXOS_KEY=cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
HYDRA_KEY=hydra.unboiled.info-1:c7i8vKOB30a+DaJ2M04F0EM8CPRfU+WpbqWie4n221M=
sudo nixos-install --root /mnt/tgt --no-root-password \
	--option substituters "$NIXOS_URL $HYDRA_URL" \
	--option trusted-public-keys "$NIXOS_KEY $HYDRA_KEY" \
	--option extra-experimental-features 'cgroups nix-command flakes' \
	--flake "$FLAKE#${HOST,,}"
