#!/usr/bin/env bash
set -Eeuo pipefail; shopt -s inherit_errexit

# disable secure boot, boot into something live

IP=$1
[[ $IP =~ [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ ]]
: "${REMOTE_USER:=root}"
hostname=quince

if ! command -v dasel >/dev/null; then
  dasel=$(nix build --print-out-paths --no-link 'nixpkgs#dasel') || exit $?
  PATH=$PATH:$dasel/bin
fi

# TODO: what's the environment we're usually reinstalling from?
ssh "$REMOTE_USER@$IP" "
  set -Eeuo pipefail; shopt -s inherit_errexit
  [[ \"\$(sudo cat /sys/devices/virtual/dmi/id/product_uuid)\" \
    == '86a6297f-1e97-124f-9435-a77e07c3508d' ]]
  [[ -e '/dev/disk/by-id/mmc-A3A444_0x1e7ca520' ]]
  [[ -e '/dev/nvme0n1' ]]
  ip a show dev enp1s0 | grep -Fq 'state UP'
  ip a show dev enp1s0 | grep -Fq 'inet $IP'
  [[ ! -e '/mnt/secrets' ]]
  if [[ ! -e .ssh ]]; then
    mkdir -p .ssh
    cat >> .ssh/authorized_keys
    chmod 600 .ssh/authorized_keys
  fi
  sudo efibootmgr --delete-bootnum -L 'UKI NixOS'
" < misc/pubkeys/ssh

# TODO: far future: also reinstall if there's no service data checked out
echo 1>&2 "THIS WILL ERASE ALL DATA ON $1!"

injdir=$(mktemp -d) || exit $?
trap 'sudo rm -rf "$injdir"' EXIT

mkdir -p "$injdir/mnt/secrets"
misc/secrets inject-to-dir "$hostname" "$injdir/mnt/secrets"
[[ -e "$injdir/mnt/secrets/login/monk" ]]
[[ -e "$injdir/mnt/secrets/login/root" ]]
[[ -e "$injdir/mnt/secrets/network-manager" ]]
[[ -e "$injdir/mnt/secrets/root.luks" ]]
[[ -e "$injdir/mnt/secrets/secureboot/KEK/KEK.key" ]]
[[ -e "$injdir/mnt/secrets/secureboot/KEK/KEK.pem" ]]
[[ -e "$injdir/mnt/secrets/secureboot/PK/PK.key" ]]
[[ -e "$injdir/mnt/secrets/secureboot/PK/PK.pem" ]]
[[ -e "$injdir/mnt/secrets/secureboot/db/db.key" ]]
[[ -e "$injdir/mnt/secrets/secureboot/db/db.pem" ]]
[[ -e "$injdir/mnt/secrets/sshd/ed25519" ]]
grep -qF 'OPENSSH PRIVATE KEY' "$injdir/mnt/secrets/sshd/ed25519"
find "$injdir/mnt/secrets" -type d -exec chmod 500 {} \;
# will be fixed up to 400 later or on latter secrets injections

mkdir "$injdir/etc"
scp -q "$REMOTE_USER@$IP:/etc/machine-id" "$injdir/etc/machine-id"

nix run 'nixpkgs#nixos-anywhere' -- \
  --extra-files "$injdir" \
  --flake "/etc/nixos#$hostname" \
  --disk-encryption-keys "/tmp/root.luks" "$injdir/mnt/secrets/root.luks" \
  "$REMOTE_USER@$IP"

sed -i "/^$IP /d" ~/.ssh/known_hosts
pubkey="$(dasel -f misc/pubkeys/sshd.toml "$hostname" -w -)"
echo "$IP $pubkey" >> ~/.ssh/known_hosts

# the promised fix-up
for i in {60..1}; do echo 1>&2 -n "$i... "; sleep 1; done
ssh "monk@$IP" 'sudo find /mnt/secrets -type d -exec chmod 400 {} \;'

# enable secure boot, redeploy
# disable all boot options but 'UKI NixOS'
# now re-lock. if it doesn't work, try just PCR 11 first, then the full set
