#!/usr/bin/env bash
set -Eeuo pipefail; shopt -s inherit_errexit

# boot nixos-latest iso, configure networking manually:
# passwd nixos
# sudo ip address add 104.152.210.200/24 dev enX0
# sudo ip route del default
# sudo ip route add default via 104.152.210.1 dev enX0
# echo 'nameserver 1.1.1.1' | sudo tee -a /etc/resolv.conf
# run this script

IP=$1
[[ $IP =~ [0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ ]]
: "${REMOTE_USER:=nixos}"
hostname=watermelon

if ! command -v dasel >/dev/null; then
  dasel=$(nix build --print-out-paths --no-link 'nixpkgs#dasel') || exit $?
  PATH=$PATH:$dasel/bin
fi

# TODO: what's the environment we're usually reinstalling from?
ssh "$REMOTE_USER@$IP" "
  set -Eeuo pipefail; shopt -s inherit_errexit
  [[ \"\$(sudo cat /sys/devices/virtual/dmi/id/product_uuid)\" \
    == '257d971b-0e27-fa20-b089-f910906d10ea' ]]
  [[ -e '/dev/xvda' ]]
  grep -Fqx 'Disk /dev/xvda: 37.6GB' <(sudo parted /dev/xvda -- print)
  ip a show dev enX0 | grep -Fq 'state UP'
  ip a show dev enX0 | grep -Fq 'inet $IP'
  grep -q NAME=NixOS /etc/os-release
  if ! grep -Fq VARIANT_ID=installer /etc/os-release; then
    cat /etc/os-release > /tmp/or
    echo VARIANT_ID=installer >> /tmp/or
    sudo mount --bind /tmp/or /etc/os-release
  fi
  grep -Fqx VARIANT_ID=installer /etc/os-release
  [[ ! -e '/mnt/secrets' ]]
  if [[ ! -e .ssh ]]; then
    mkdir -p .ssh
    cat >> .ssh/authorized_keys
    chmod 600 .ssh/authorized_keys
  fi
" < misc/pubkeys/ssh

# TODO: far future: also reinstall if there's no service data checked out
echo 1>&2 "THIS WILL ERASE AT LEAST SOME DRIVES OF $1!"

injdir=$(mktemp -d) || exit $?
trap 'sudo rm -rf "$injdir"' EXIT

mkdir -p "$injdir/mnt/secrets"
misc/secrets inject-to-dir "$hostname" "$injdir/mnt/secrets"
[[ -e "$injdir/mnt/secrets/login/monk" ]]
[[ -e "$injdir/mnt/secrets/login/root" ]]
[[ -e "$injdir/mnt/secrets/sshd/ed25519" ]]
grep -qF 'OPENSSH PRIVATE KEY' "$injdir/mnt/secrets/sshd/ed25519"
find "$injdir/mnt/secrets" -type d -exec chmod 500 {} \;
# will be fixed up to 400 later or on latter secrets injections

mkdir "$injdir/etc"
scp -q "$REMOTE_USER@$IP:/etc/machine-id" "$injdir/etc/machine-id"

nix run 'nixpkgs#nixos-anywhere' -- \
  --extra-files "$injdir" \
  --flake "/etc/nixos#$hostname" \
  --kexec /dev/null \
  "$REMOTE_USER@$IP"

sed -i "/^$IP /d" ~/.ssh/known_hosts
pubkey="$(dasel -f misc/pubkeys/sshd.toml "$hostname" -w -)"
echo "$IP $pubkey" >> ~/.ssh/known_hosts

# the promised fix-up
for i in {180..1}; do echo 1>&2 -n "$i... "; sleep 1; done
ssh "monk@$IP" 'sudo find /mnt/secrets -type d -exec chmod 400 {} \;'
