araceae = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDWPAwt2xHO9d7Tx8PNQpewC+VgHkzVl8ws16tqmQKAl"
bayroot = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILkFPelEKV/vSA38n1IiCMHVZ0e7PIDpoyo/6Y0aiein"
cocoa = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPIWrEL3E4FAnOxfL/fFx+byE45f5y0dogghVtC3Zeay cocoa"
duckweed = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIASTR5SavefPqRkeTrI6bbMNp6AFnf4wHA5Lxo72H/wJ"
etrog = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO1ii+4fTGmHhdOcLe44B7YAup+wSCFer3bkJmOj+tud etrog"
fig = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJqgedUvuPRTMLbhpz9IXKH03TdTnQVwdLsMpbTyBb4u"
grapefruit = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICHLMdijanilYxEG8Qgffguo//Sp++j5WfkBoUNMbZ3x grapefruit"
iyokan = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG0qPqDNul1u1cGL1QOynlpucuqv76qEyC3w812ac51V iyokan"
loquat = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKBra/oIenaBvFOtNsF97uUrWRakng1R1zcJyy0/MoR8 loquat"
lychee = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFs8HSQs9jb+TORQ+BphdG3BAvJayFrcDWUune4prNWc lychee"
olosapo = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKShxkVutX/8mgxS/1rRMrgxmePyfu3m31ZDWJxSxfD8 olosapo"
quince = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHJJJaBj6vAKjZJ9dlIS6q4qMPV63J7dyInV7iqwMkwp quince"
sloe = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDu+6P0zkyAaOi7xliGtpITG+dUPdHZe2j7IDZtSolRc sloe"
spondias = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAQ8kFWaSxCjFit6oOSV/ZEa+Xx0lhqkRcGyKNc+EHcT spondias"
watermelon = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEHPn0bVjvySMOvV6j30iS2krhoThB+os0VyB9rDjYNb watermelon"
plum = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINuhpgUntiyGDnuQl2eL0Mjv6hvJL0rxkPbhBs6B/val plum"
