cocoa = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPIWrEL3E4FAnOxfL/fFx+byE45f5y0dogghVtC3Zeay cocoa'
etrog = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIO1ii+4fTGmHhdOcLe44B7YAup+wSCFer3bkJmOj+tud etrog'
olosapo = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKShxkVutX/8mgxS/1rRMrgxmePyfu3m31ZDWJxSxfD8 olosapo'
quince = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHJJJaBj6vAKjZJ9dlIS6q4qMPV63J7dyInV7iqwMkwp quince'
sloe = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDu+6P0zkyAaOi7xliGtpITG+dUPdHZe2j7IDZtSolRc sloe'
watermelon = 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEHPn0bVjvySMOvV6j30iS2krhoThB+os0VyB9rDjYNb watermelon'
