carambola = 'ZSZYIF3-777DCOZ-2ZGLV6E-AADEDAR-X5ITTDC-IK55LPN-AIG7IAG-B5ZGYQE'
fig = 'NDGEKVE-3EP5FBF-3KJU3UE-ZFOETAY-T3P3QPR-5VKSGS5-TLUQHUC-KKQECQZ'
quince = 'QE2PZOE-RAH6EYI-UMAV6HY-M4ERNJV-SSJQGPK-NYLETWI-SXXKXMW-W764IQK'
