carambola = 'ZSZYIF3-777DCOZ-2ZGLV6E-AADEDAR-X5ITTDC-IK55LPN-AIG7IAG-B5ZGYQE'
cocoa = 'MTB3L25-WO465UX-ZQBTETR-IIXTRK3-BZCIJEB-UP2IGCF-JJC3ROG-KSMLVAF'
coconut = 'P26PXVC-DMYANKV-45P2EB6-FO5HT4E-VLDMPIZ-DPN7YE7-MGCV4SP-UVJJ7QD'
fig = 'NDGEKVE-3EP5FBF-3KJU3UE-ZFOETAY-T3P3QPR-5VKSGS5-TLUQHUC-KKQECQZ'
lychee = 'B3XZPL6-3B6IPHZ-DQ5RCVI-RN3YUJW-WBCK765-KRDVGFI-BT33F7X-J5CJIA7'
olosapo = 'CJJA75Z-F36J6RX-S4XQKRV-KSKGDSD-34DK2EU-2MJILXX-LERNQPA-NDTCXQP'
quince = 'QE2PZOE-RAH6EYI-UMAV6HY-M4ERNJV-SSJQGPK-NYLETWI-SXXKXMW-W764IQK'
sloe = '5LEPV6G-D26N5JF-4G64CPI-AJU4GC5-7ZIBLD5-RHNTEFS-VRWCEQZ-GZLB7AV'
tamarillo = 'MDONNYE-PWXZPJB-QMNJ7SZ-WDLKA6O-JGPM4TD-YVUC3ES-O2XJ7ZL-HZT4BAL'
watermelon = '2GDCVTH-IQ6JV2F-I4C6YM3-TIXVXZ2-OYLDTDS-6UGUW5K-6ZC2AX7-5ZABFAL'
