# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d32c16a6-1ef2-4873-ad72-65b99b544b61";
      fsType = "xfs";
    };

  boot.initrd.luks.devices."colaroot".device = "/dev/disk/by-uuid/50dd953d-f039-496e-909c-2fe202eb0c6c";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DEB8-4B51";
      fsType = "vfat";
    };

  swapDevices = [ ];

}
