#!/bin/sh
# ./update.sh add t184256/vim-boring
# ./update.sh update
mkdir -p ./pkgs/applications/editors/vim/plugins/
echo '{}' > ./pkgs/applications/editors/vim/plugins/deprecated.json
mv ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/generated.nix \
   ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/generated.nix.bak
mv ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/overrides.nix \
   ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/overrides.nix.bak
echo '_: self: super: {}' \
   > ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/overrides.nix
cat > ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/generated.nix <<EOF
# GENERATED by ./overlays/vim-plugins/update.sh. Do not edit!
{ lib, buildVimPlugin, buildNeovimPlugin, fetchFromGitHub }:

final: prev:
{
}
EOF
mv ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/vim-plugin-names \
   ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/vim-plugin-names.bak
mv ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/vim-plugin-names \
   ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/vim-plugin-names.bak

nix run 'nixpkgs#vimPluginsUpdater' -- \
        --debug DEBUG \
        --nixpkgs ~/code/nixpkgs --proc 1 --no-commit \
        --input-names list.csv --out generated.nix "$@"
ret=$?

mv ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/vim-plugin-names.bak \
   ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/vim-plugin-names
mv ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/generated.nix.bak \
   ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/generated.nix
mv ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/overrides.nix.bak \
   ~/code/nixpkgs/pkgs/applications/editors/vim/plugins/overrides.nix

rm -d ./pkgs/applications/editors/vim/plugins/deprecated.json
rm -d ./pkgs/applications/editors/vim/plugins
rm -d ./pkgs/applications/editors/vim
rm -d ./pkgs/applications/editors
rm -d ./pkgs/applications
rm -d ./pkgs
exit $ret
