{ pkgs, config, ... }:

{
  imports = [ ./config/no-graphics.nix ./config/os.nix ];

  # manual bits:
  # * logging into sync
  # * toolbar customization
  programs = if config.system.noGraphics then {} else {
    browserpass = { enable = true; browsers = [ "firefox" ]; };
    firefox = {
      enable = config.system.os == "NixOS";
      package = pkgs.firefox.override {
        cfg = {
          enableGnomeExtensions = true;
        };
      };
      profiles.default = {
        settings = {
          # extra finicky ones
          "browser.uiCustomization.horizontalTabstrip" =
            "[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]";
          "browser.uiCustomization.state" = "{" + (
            "\"placements\":{" + (
              "\"widget-overflow-fixed-list\":[]," +
              "\"unified-extensions-area\":[" + (
                "\"ublock0_raymondhill_net-browser-action\"," +
                "\"streetpass_streetpass_social-browser-action\"," +
                "\"browserpass_maximbaz_com-browser-action\"," +
                "\"addon_darkreader_org-browser-action\"," +
                "\"chrome-gnome-shell_gnome_org-browser-action\"," +
                "\"jid1-kkzogwgsw3ao4q_jetpack-browser-action\""
              ) + "]," +
              "\"nav-bar\":[" + (
                "\"sidebar-button\"," +  # assumes its place 2nd time?..
                "\"vertical-spacer\"," +
                "\"back-button\"," +
                "\"forward-button\"," +
                #"\"stop-reload-button\"," +
                "\"urlbar-container\"," +
                "\"unified-extensions-button\"," +
                "\"vertical-spacer\""
              ) + "]," +
              "\"toolbar-menubar\":[\"menubar-items\"]," +
              "\"TabsToolbar\":[]," +
              "\"vertical-tabs\":[\"tabbrowser-tabs\"]," +
              "\"PersonalToolbar\":[" + (
                "\"import-button\"," +
                "\"personal-bookmarks\""
              ) + "]"
            ) + "}," +
            "\"seen\":[\"developer-button\"]," +
            "\"dirtyAreaCache\":[" + (
              "\"nav-bar\"," +
              "\"TabsToolbar\"," +
              "\"vertical-tabs\"," +
              "\"PersonalToolbar\"," +
              "\"toolbar-menubar\"" +
              "],"
            ) +
            "\"currentVersion\":22," +
            "\"newElementCount\":1" +
            "}"
          );
          "sidebar.backupState" = "{" + (
            "\"panelOpen\":false," +
            "\"launcherWidth\":57," +
            "\"launcherExpanded\":false," +
            "\"launcherVisible\":true"
          ) + "}";
          "sidebar.main.tools" = "";  # aichat,syncedtabs,history,bookmarks
          "sidebar.new-sidebar.has-used" = true;
          "sidebar.revamp" = true;
          "sidebar.visibility" = "always-show";
          "sidebar.verticalTabs" = true;

          "browser.compactmode.show" = 1;
          "browser.display.use_document_fonts" = 0;
          "browser.download.useDownloadDir" = false;  # ask where to save
          "browser.newtabpage.enabled" = false;  # see showSponsored/telemetry
          "browser.safebrowsing.downloads.remote.enabled" = false;
          "browser.search.suggest.enabled" = false;
          "browser.startup.homepage" = "about:blank";
          "browser.startup.page" = 3;  # restore session
          "browser.tabs.closeWindowWithLastTab" = 0;
          "browser.tabs.drawInTitlebar" = false;  # kills the close button
          "browser.toolbars.bookmarks.visibility" = "never";
          "browser.uidensity" = 1;  # compact, let's see how long will it last
          "extensions.activeThemeID" = "firefox-compact-dark@mozilla.org";
          "extensions.formautofill.creditCards.available" = false;
          "extensions.formautofill.creditCards.enabled" = false;
          "gfx.webrender.all" = true;
          "media.ffmpeg.vaapi.enabled" = true;
          "pdfjs.enableScripting" = false;
          "services.sync.engine.creditcards" = false;
          "services.sync.engine.creditcards.available" = false;
          "services.sync.engine.passwords" = false;
          "signon.rememberSignons" = false;
          "toolkit.legacyUserProfileCustomizations.stylesheets" = true;
          # bug: popups don't go away
          #"gfx.webrender.compositor" = true;
          #"gfx.webrender.compositor.force-enabled" = true;

          # generated by https://ffprofile.com
          "app.normandy.api_url" = "";
          "app.normandy.enabled" = false;
          "app.shield.optoutstudies.enabled" = false;
          "app.update.auto" = false;
          "beacon.enabled" = false;
          "breakpad.reportURL" = "";
          "browser.aboutConfig.showWarning" = false;
          "browser.cache.offline.enable" = false;
          "browser.crashReports.unsubmittedCheck.autoSubmit" = false;
          "browser.crashReports.unsubmittedCheck.autoSubmit2" = false;
          "browser.crashReports.unsubmittedCheck.enabled" = false;
          "browser.disableResetPrompt" = true;
          "browser.newtab.preload" = false;
          "browser.newtabpage.activity-stream.section.highlights.includePocket" = false;
          "browser.newtabpage.enhanced" = false;
          "browser.newtabpage.introShown" = true;
          "browser.selfsupport.url" = "";
          "browser.send_pings" = false;
          "browser.sessionstore.privacy_level" = 2;
          "browser.shell.checkDefaultBrowser" = false;
          "browser.startup.homepage_override.mstone" = "ignore";
          "browser.tabs.crashReporting.sendReport" = false;
          "browser.urlbar.trimURLs" = false;
          "datareporting.healthreport.service.enabled" = false;
          "datareporting.healthreport.uploadEnabled" = false;
          "datareporting.policy.dataSubmissionEnabled" = false;
          "device.sensors.ambientLight.enabled" = false;
          "device.sensors.enabled" = false;
          "device.sensors.motion.enabled" = false;
          "device.sensors.orientation.enabled" = false;
          "device.sensors.proximity.enabled" = false;
          "dom.battery.enabled" = false;
          "dom.event.clipboardevents.enabled" = false;
          "dom.private-attribution.submission.enabled" = false;
          "experiments.activeExperiment" = false;
          "experiments.enabled" = false;
          "experiments.manifest.uri" = "";
          "experiments.supported" = false;
          "extensions.CanvasBlocker@kkapsner.de.whiteList" = "";
          "extensions.ClearURLs@kevinr.whiteList" = "";
          "extensions.getAddons.cache.enabled" = false;
          "extensions.getAddons.showPane" = false;
          "extensions.pocket.enabled" = false;
          "extensions.screenshots.upload-disabled" = true;
          "extensions.shield-recipe-client.api_url" = "";
          "extensions.shield-recipe-client.enabled" = false;
          "extensions.webservice.discoverURL" = "";
          "media.autoplay.default" = 1;
          "media.autoplay.enabled" = false;
          "media.eme.enabled" = false;
          "media.gmp-widevinecdm.enabled" = false;
          "media.video_stats.enabled" = false;
          "network.allow-experiments" = false;
          "network.cookie.cookieBehavior" = 1;
          "network.http.referer.spoofSource" = true;
          "privacy.donottrackheader.enabled" = true;
          "privacy.donottrackheader.value" = 1;
          "privacy.firstparty.isolate" = true;
          "privacy.trackingprotection.cryptomining.enabled" = true;
          "privacy.trackingprotection.enabled" = true;
          "privacy.trackingprotection.fingerprinting.enabled" = true;
          "privacy.trackingprotection.pbmode.enabled" = true;
          "security.ssl.disable_session_identifiers" = true;
          "services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSite" = false;
          "signon.autofillForms" = false;
          "toolkit.telemetry.archive.enabled" = false;
          "toolkit.telemetry.bhrPing.enabled" = false;
          "toolkit.telemetry.cachedClientID" = "";
          "toolkit.telemetry.enabled" = false;
          "toolkit.telemetry.firstShutdownPing.enabled" = false;
          "toolkit.telemetry.hybridContent.enabled" = false;
          "toolkit.telemetry.newProfilePing.enabled" = false;
          "toolkit.telemetry.prompted" = 2;
          "toolkit.telemetry.rejected" = true;
          "toolkit.telemetry.reportingpolicy.firstRun" = false;
          "toolkit.telemetry.server" = "";
          "toolkit.telemetry.shutdownPingSender.enabled" = false;
          "toolkit.telemetry.unified" = false;
          "toolkit.telemetry.unifiedIsOptIn" = false;
          "toolkit.telemetry.updatePing.enabled" = false;
        };
        # Best debugged in Style Editor of the Browser Toolbox
        userChrome = ''
          /* sidebar: gear icon + other tool icons */
          .tools-and-extensions.actions-list { display: none !important; }
          /* more sidebar tweaks */
          #tabbrowser-arrowscrollbox { min-width: 0 !important; }
          .tools-and-extensions.actions-list { display: none !important; }
          /* make the toolbar expander element narrower */
          toolbar toolbarspring {
            -moz-box-flex: 40 !important;
            min-width: 10px !important;
            max-width: 24px !important;
          }
          /* sidebar more flush to the left (was 8 px) */
          #sidebar-button {
            padding-left: 2px !important;
            padding-right: 2px !important;
          }
          /* large-yet-compact side-tabs */
          tabs#tabbrowser-tabs[orient="vertical"] {
            --icon-size-default: 24px;
            --tab-pinned-min-width-expanded: 24px;
            --tab-pinned-container-margin-inline-expanded: 0px;
            --tab-inner-inline-margin: 1px;
            --tab-collapsed-background-width: 24px;
            --tab-collapsed-width: 32px;
            --tab-icon-end-margin: 4px;
            --tab-inline-padding: 0px !important;
            --button-border-radius: 0px;
            padding-block: 1px !important;
          }
          #vertical-pinned-tabs-container > tab.tabbrowser-tab {
            max-width: 32px !important;
          }
          .tab-content {
            padding-left: 4px !important;
            padding-right: 4px !important;
          }
          vbox.tab-background {
            margin: 0px 1px !important;
            border-radius: 0px !important;
            min-width: 30px;
            /*outline-color: green;*/ /* debugging aid */
          }
          label.tab-text {
            font-size: 90%;
          }
          #tabbrowser-arrowscrollbox-periphery {
            display: none !important;
          }
          .tab-icon-image {
            width: 24px !important;
            height: 24px !important;
          }
          image.tab-close-button {
            border-radius: 0px !important;
            padding: 0 !important;
            margin-right: 1px !important;
            width: 12px !important;
            height: 12px !important;
          }
          #vertical-pinned-tabs-container-separator {
            display: none !important;
            margin: 0 !important;
          }
        '';
      };
    };
  };
}
