{ pkgs, config, ... }:

{
  imports = [ ./config/no-graphics.nix ];

  # manual bits:
  # * logging into sync
  # * toolbar customization
  programs = if config.system.noGraphics then {} else {
    browserpass = { enable = true; browsers = [ "firefox" ]; };
    firefox = {
      enable = true;
      package = pkgs.firefox-wayland.override {
        cfg = {
          enableGnomeExtensions = true;
        };
      };
      profiles.default = {
        settings = {
          "browser.display.use_document_fonts" = 0;
          "browser.download.useDownloadDir" = false;  # ask where to save
          "browser.newtabpage.enabled" = false;
          "browser.search.suggest.enabled" = false;
          "browser.startup.homepage" = "about:blank";
          "browser.startup.page" = 3;  # restore session
          "browser.tabs.closeWindowWithLastTab" = 0;
          "browser.tabs.drawInTitlebar" = false;  # kills the close button
          "browser.toolbars.bookmarks.visibility" = "never";
          "browser.uidensity" = 1;  # compact, let's see how long will it last
          "extensions.activeThemeID" = "firefox-compact-dark@mozilla.org";
          "extensions.formautofill.creditCards.available" = false;
          "extensions.formautofill.creditCards.enabled" = false;
          "services.sync.engine.creditcards" = false;
          "services.sync.engine.creditcards.available" = false;
          "services.sync.engine.passwords" = false;
          "signon.rememberSignons" = false;
          "toolkit.legacyUserProfileCustomizations.stylesheets" = true;

          # generated by https://ffprofile.com
          "app.normandy.api_url" = "";
          "app.normandy.enabled" = false;
          "app.shield.optoutstudies.enabled" = false;
          "app.update.auto" = false;
          "beacon.enabled" = false;
          "breakpad.reportURL" = "";
          "browser.aboutConfig.showWarning" = false;
          "browser.cache.offline.enable" = false;
          "browser.crashReports.unsubmittedCheck.autoSubmit" = false;
          "browser.crashReports.unsubmittedCheck.autoSubmit2" = false;
          "browser.crashReports.unsubmittedCheck.enabled" = false;
          "browser.disableResetPrompt" = true;
          "browser.newtab.preload" = false;
          "browser.newtabpage.activity-stream.section.highlights.includePocket" = false;
          "browser.newtabpage.enhanced" = false;
          "browser.newtabpage.introShown" = true;
          "browser.selfsupport.url" = "";
          "browser.send_pings" = false;
          "browser.sessionstore.privacy_level" = 2;
          "browser.shell.checkDefaultBrowser" = false;
          "browser.startup.homepage_override.mstone" = "ignore";
          "browser.tabs.crashReporting.sendReport" = false;
          "browser.urlbar.trimURLs" = false;
          "datareporting.healthreport.service.enabled" = false;
          "datareporting.healthreport.uploadEnabled" = false;
          "datareporting.policy.dataSubmissionEnabled" = false;
          "device.sensors.ambientLight.enabled" = false;
          "device.sensors.enabled" = false;
          "device.sensors.motion.enabled" = false;
          "device.sensors.orientation.enabled" = false;
          "device.sensors.proximity.enabled" = false;
          "dom.battery.enabled" = false;
          "dom.event.clipboardevents.enabled" = false;
          "experiments.activeExperiment" = false;
          "experiments.enabled" = false;
          "experiments.manifest.uri" = "";
          "experiments.supported" = false;
          "extensions.CanvasBlocker@kkapsner.de.whiteList" = "";
          "extensions.ClearURLs@kevinr.whiteList" = "";
          "extensions.getAddons.cache.enabled" = false;
          "extensions.getAddons.showPane" = false;
          "extensions.pocket.enabled" = false;
          "extensions.screenshots.upload-disabled" = true;
          "extensions.shield-recipe-client.api_url" = "";
          "extensions.shield-recipe-client.enabled" = false;
          "extensions.webservice.discoverURL" = "";
          "media.autoplay.default" = 1;
          "media.autoplay.enabled" = false;
          "media.eme.enabled" = false;
          "media.gmp-widevinecdm.enabled" = false;
          "media.video_stats.enabled" = false;
          "network.allow-experiments" = false;
          "network.cookie.cookieBehavior" = 1;
          "network.http.referer.spoofSource" = true;
          "privacy.donottrackheader.enabled" = true;
          "privacy.donottrackheader.value" = 1;
          "privacy.firstparty.isolate" = true;
          "privacy.trackingprotection.cryptomining.enabled" = true;
          "privacy.trackingprotection.enabled" = true;
          "privacy.trackingprotection.fingerprinting.enabled" = true;
          "privacy.trackingprotection.pbmode.enabled" = true;
          "security.ssl.disable_session_identifiers" = true;
          "services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSite" = false;
          "signon.autofillForms" = false;
          "toolkit.telemetry.archive.enabled" = false;
          "toolkit.telemetry.bhrPing.enabled" = false;
          "toolkit.telemetry.cachedClientID" = "";
          "toolkit.telemetry.enabled" = false;
          "toolkit.telemetry.firstShutdownPing.enabled" = false;
          "toolkit.telemetry.hybridContent.enabled" = false;
          "toolkit.telemetry.newProfilePing.enabled" = false;
          "toolkit.telemetry.prompted" = 2;
          "toolkit.telemetry.rejected" = true;
          "toolkit.telemetry.reportingpolicy.firstRun" = false;
          "toolkit.telemetry.server" = "";
          "toolkit.telemetry.shutdownPingSender.enabled" = false;
          "toolkit.telemetry.unified" = false;
          "toolkit.telemetry.unifiedIsOptIn" = false;
          "toolkit.telemetry.updatePing.enabled" = false;
        };
        userChrome = ''
          #nav-bar.browser-toolbar {
            background: var(--button-hover-bgcolor) !important;
          }
          .tabbrowser-tab[selected=true] {
            background: var(--button-hover-bgcolor) !important;
          }
          .tab-background {
            background: unset !important; box-shadow: unset !important;
          }
          @media (-moz-proton) {
              .tab-background {
                  border-radius: var(--user-tab-rounding) var(--user-tab-rounding) 0px 0px !important;
                  margin-block: 1px 0 !important;
              }
              /* Container color bar visibility */
              .tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-context-line {
                  margin: 0px max(-3px, 0px) !important;
              }
          }
        '';
      };
    };
  };
}
